import AVFoundation
import Foundation

// split-spike <input.(mp3|m4a|wav)> "0:00,2:36,4:44" [--codec aac|alac] [--bitrate 256] [--out DIR] [--no-verify]
//
// Phase 0 feasibility spike (implementation.md §12, §13). Streams a decode of `input`, splits it at
// the given timestamps into per-track .m4a files with full iTunes metadata + artwork, then verifies
// gapless structure by decoding the outputs back and comparing frame counts / seams to the source.

func fail(_ msg: String) -> Never {
    FileHandle.standardError.write(Data((msg + "\n").utf8))
    exit(2)
}

func parseTimestamp(_ s: String) -> Double? {
    let parts = s.split(separator: ":").map(String.init)
    guard parts.allSatisfy({ Int($0) != nil }) else { return nil }
    switch parts.count {
    case 2: return Double(parts[0])! * 60 + Double(parts[1])!
    case 3: return Double(parts[0])! * 3600 + Double(parts[1])! * 60 + Double(parts[2])!
    default: return nil
    }
}

let argv = CommandLine.arguments
guard argv.count >= 3 else {
    fail("usage: split-spike <input> \"0:00,2:36,4:44\" [--codec aac|alac] [--bitrate 256] [--out DIR] [--no-verify]")
}

let inputURL = URL(fileURLWithPath: (argv[1] as NSString).expandingTildeInPath).standardizedFileURL
guard FileManager.default.fileExists(atPath: inputURL.path) else { fail("input not found: \(inputURL.path)") }

let boundarySeconds = argv[2].split(separator: ",").map { s -> Double in
    guard let v = parseTimestamp(s.trimmingCharacters(in: .whitespaces)) else { fail("bad timestamp: \(s)") }
    return v
}

var codec: SpikeCodec = .aac
var bitrate = 256
var outDir = URL(fileURLWithPath: FileManager.default.currentDirectoryPath).appendingPathComponent("spike-out")
var verify = true
var i = 3
while i < argv.count {
    switch argv[i] {
    case "--codec":
        guard i + 1 < argv.count, let c = SpikeCodec(rawValue: argv[i + 1]) else { fail("--codec aac|alac") }
        codec = c; i += 2
    case "--bitrate":
        guard i + 1 < argv.count, let b = Int(argv[i + 1]) else { fail("--bitrate <int>") }
        bitrate = b; i += 2
    case "--out":
        guard i + 1 < argv.count else { fail("--out DIR") }
        outDir = URL(fileURLWithPath: (argv[i + 1] as NSString).expandingTildeInPath); i += 2
    case "--no-verify":
        verify = false; i += 1
    default:
        fail("unknown arg: \(argv[i])")
    }
}

let album = SpikeAlbumMetadata(
    album: "SetSplitter Phase 0 Spike",
    albumArtist: "Various Artists",
    year: 2026,
    genre: "Electronic",
    comment: "Generated by split-spike",
    artworkJPEG: ArtworkStub.makeJPEG(),
    gaplessAlbum: true,
    compilation: false)

let trackCount = boundarySeconds.filter { $0 > 0 }.count + 1
let titles = (1...trackCount).map { "Spike Part \($0)" }
let artists = (1...trackCount).map { _ in "Test Artist" }

let cfg = SpikeConfig(
    input: inputURL,
    boundarySeconds: boundarySeconds,
    codec: codec,
    aacBitrateKbps: bitrate,
    outputDir: outDir,
    album: album,
    trackTitles: titles,
    trackArtists: artists)

print("== split-spike ==")
print("input      : \(inputURL.path)")
print("boundaries : \(boundarySeconds) s")
print("codec      : \(codec.rawValue)\(codec == .aac ? " \(bitrate) kbps" : "")")
print("out        : \(outDir.path)")
print("artwork    : \(album.artworkJPEG.map { "\($0.count) bytes JPEG" } ?? "none")")
print("")

let result: SpikeResult
do {
    result = try Spike.run(cfg)
} catch {
    fail("split failed: \(error)")
}

print("-- split --")
print("source sample rate : \(result.sourceSampleRate) Hz, channels: \(result.sourceChannels)")
print("frames decoded     : \(result.framesDecoded)")
print("frames from duration: \(result.expectedFramesFromDuration)  (Q3 delta: \(result.framesDecoded - result.expectedFramesFromDuration))")
print("boundary frames    : \(result.boundaryFrames)")
print("per-track frames   : \(result.perTrackFrames)  sum=\(result.perTrackFrames.reduce(0, +))")
print("split path (Q4)    : API worked=\(result.apiSplitPathWorked) manualFallbackUsed=\(result.usedManualSplitPath)")
print("peak footprint (Q5): \(MemorySampler.mb(result.peakFootprint))")
print(String(format: "wall clock (Q6)   : %.2f s for %.1f s of audio  (=> ~%.0f s projected for 2 h)",
             result.wallClock,
             Double(result.framesDecoded) / result.sourceSampleRate,
             result.wallClock / (Double(result.framesDecoded) / result.sourceSampleRate) * 7200))
print("outputs:")
for u in result.outputURLs {
    let sz = (try? FileManager.default.attributesOfItem(atPath: u.path)[.size] as? Int) ?? nil
    print("  \(u.lastPathComponent)  (\(sz.map { "\($0) bytes" } ?? "?"))")
}
print("")

// MARK: metadata readback  (Q1, Q2)

func loadMetadata(_ url: URL) -> [AVMetadataItem] {
    let asset = AVURLAsset(url: url)
    let sem = DispatchSemaphore(value: 0)
    var items: [AVMetadataItem] = []
    Task {
        items = (try? await asset.load(.metadata)) ?? []
        sem.signal()
    }
    sem.wait()
    return items
}

if let first = result.outputURLs.first {
    print("-- metadata readback via AVAsset.load(.metadata): \(first.lastPathComponent) --")
    for item in loadMetadata(first) {
        let id = item.identifier?.rawValue ?? "\(item.keySpace?.rawValue ?? "?"):\(item.key ?? "?" as NSCopying & NSObjectProtocol)"
        let val: String
        if let s = blockingLoad({ try await item.load(.stringValue) }) { val = "\"\(s)\"" }
        else if let n = blockingLoad({ try await item.load(.numberValue) }) { val = "num \(n)" }
        else if let d = blockingLoad({ try await item.load(.dataValue) }) {
            val = "data[\(d.count)] " + d.prefix(12).map { String(format: "%02x", $0) }.joined(separator: " ")
        }
        else { val = "?" }
        print("  \(id) = \(val)")
    }
    print("")

    print("-- raw ilst atom walk (real on-disk bytes): \(first.lastPathComponent) --")
    let entries = AtomInspector.dumpILST(url: first)
    if entries.isEmpty { print("  (no metadata atoms found — RED FLAG)") }
    for e in entries {
        print("  \(e.path)  [\(e.note)]")
        let hexBytes = e.payloadHex.split(separator: " ")
        let shown = hexBytes.count > 48 ? hexBytes.prefix(48).joined(separator: " ") + " … (+\(hexBytes.count - 48) bytes)" : e.payloadHex
        print("    hex: \(shown)")
        if e.path.contains("trkn") {
            print("    ^ Q1 expected shape: 00 00 <idx BE16> <total BE16> 00 00")
        }
        if e.path.contains("pgap") {
            print("    ^ Q2: pgap atom present on disk => gapless flag written")
        }
    }
    print("")

    // ffprobe second opinion if present.
    let probe = Process()
    probe.executableURL = URL(fileURLWithPath: "/opt/homebrew/bin/ffprobe")
    if FileManager.default.fileExists(atPath: probe.executableURL!.path) {
        probe.arguments = ["-hide_banner", "-v", "error", "-show_entries",
                           "format_tags:stream_tags", "-of", "default=noprint_wrappers=1", first.path]
        let pipe = Pipe()
        probe.standardOutput = pipe
        try? probe.run()
        probe.waitUntilExit()
        let out = String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
        print("-- ffprobe tags --")
        print(out.split(separator: "\n").map { "  " + $0 }.joined(separator: "\n"))
        print("")
    }
}

// MARK: gapless / concat verification  (§7, Q2, Q3)

if verify {
    print("-- concat verification --")
    // cumulative boundary frames in the source for seam probing
    var cum: [Int] = []
    var acc = 0
    for f in result.perTrackFrames.dropLast() { acc += f; cum.append(acc) }
    do {
        let r = try ConcatVerifier.verify(source: inputURL, outputs: result.outputURLs, boundaryFramesInSource: cum)
        print("source frames          : \(r.sourceFrames)")
        print("output frames (concat) : \(r.outputFramesTotal)")
        print("per-file frames        : \(r.perFileFrames)")
        print("FRAME DELTA            : \(r.frameDelta)   \(r.frameDelta == 0 ? "✅ gapless proven structurally" : "⚠️ mismatch")")
        print(String(format: "whole-file max |Δ|     : %.6g  %@", r.wholeFileMaxAbsDiff,
                     r.bitExact ? "✅ bit-exact" : (codec == .alac ? "⚠️ ALAC not bit-exact" : "(expected for lossy AAC)")))
        print("Q3 reader vs duration  : source=\(r.sourceFrames) durationFrames=\(r.expectedFramesFromDuration) delta=\(r.readerDurationDelta)")
        for s in r.seams {
            print(String(format: "  seam @ frame %d: maxΔ vs src=%.5f rms=%.5f | seamJump=%.5f typicalJump=%.5f  %@",
                         s.boundaryFrame, s.maxAbsDiffVsSource, s.rmsVsSource,
                         s.maxAdjacentJumpAtSeam, s.typicalAdjacentJump,
                         s.maxAdjacentJumpAtSeam <= max(s.typicalAdjacentJump * 8, 0.02) ? "✅ no click" : "⚠️ possible click"))
        }
    } catch {
        print("  verification error: \(error)")
    }
    print("")
}

print("done. drag \(outDir.path) into Music to eyeball Get Info + listen for seams.")
