# SetSplitter — see implementation.md §12 (Phase 1)
# The .xcodeproj is generated by XcodeGen from project.yml and is gitignored.
# Never hand-edit it; edit project.yml and run `make gen`.

PROJECT      := SetSplitter.xcodeproj
SCHEME       := SetSplitter
CONFIG       := Debug
CORE_PKG     := Packages/SetSplitterCore
DERIVED_DATA := .build/DerivedData

.PHONY: gen build test run clean

gen:
	xcodegen generate

build: gen
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) -configuration $(CONFIG) \
		-derivedDataPath $(DERIVED_DATA) \
		CODE_SIGNING_ALLOWED=NO build

test:
	cd $(CORE_PKG) && swift test

run: build
	open $(DERIVED_DATA)/Build/Products/$(CONFIG)/$(SCHEME).app

clean:
	rm -rf $(DERIVED_DATA) $(PROJECT)
	cd $(CORE_PKG) && swift package clean
