# SetSplitter — see implementation.md §12 (Phase 1)
# The .xcodeproj is generated by XcodeGen from project.yml and is gitignored.
# Never hand-edit it; edit project.yml and run `make gen`.

PROJECT      := SetSplitter.xcodeproj
SCHEME       := SetSplitter
CONFIG       := Debug
CORE_PKG     := Packages/SetSplitterCore
DERIVED_DATA := .build/DerivedData

.PHONY: gen build build-signed test test-app run snapshots clean

gen:
	xcodegen generate

build: gen
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) -configuration $(CONFIG) \
		-derivedDataPath $(DERIVED_DATA) \
		CODE_SIGNING_ALLOWED=NO build

test:
	cd $(CORE_PKG) && swift test

# App-layer tests (SessionStore, view models). Signed ad hoc so the sandboxed host app can load the test bundle.
test-app: gen
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) -configuration $(CONFIG) \
		-derivedDataPath $(DERIVED_DATA) \
		CODE_SIGN_IDENTITY=- CODE_SIGNING_ALLOWED=YES CODE_SIGNING_REQUIRED=YES test

# Ad-hoc *signed* build: unlike `build`, the entitlements apply, so the App
# Sandbox is really on. Use this (not `build`) when checking file access.
build-signed: gen
	xcodebuild -project $(PROJECT) -scheme $(SCHEME) -configuration $(CONFIG) \
		-derivedDataPath $(DERIVED_DATA) \
		CODE_SIGN_IDENTITY=- CODE_SIGNING_ALLOWED=YES CODE_SIGNING_REQUIRED=YES build

run: build-signed
	open $(DERIVED_DATA)/Build/Products/$(CONFIG)/$(SCHEME).app

# Render every wizard state to PNGs (light + dark) headlessly; see App/Debug/SnapshotRunner.swift.
snapshots: build
	$(DERIVED_DATA)/Build/Products/$(CONFIG)/$(SCHEME).app/Contents/MacOS/$(SCHEME) --snapshot $(or $(OUT),.build/snapshots)

clean:
	rm -rf $(DERIVED_DATA) $(PROJECT)
	cd $(CORE_PKG) && swift package clean
